### ISSUE TITLE
Solr doesn't seem to have started?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3_deploy#14]
I'm guessing that would be the responsibility of capistrano?

Actually, just getting the solr config in place doesn't seem to have happened, and when I try by hand:
```
[ec2-user@ip-10-168-152-48 current]$ bundle exec rake jetty:config
rake aborted!
LoadError: cannot load such file -- rspec/core/rake_task
/var/www/openvault/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
/var/www/openvault/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `block in require'
/var/www/openvault/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/www/openvault/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
/var/www/openvault/releases/20160224194135/lib/tasks/ci.rake:4:in `<top (required)>'
/var/www/openvault/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:241:in `load'
/var/www/openvault/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:241:in `block in load'
/var/www/openvault/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/www/openvault/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:241:in `load'
/var/www/openvault/shared/bundle/ruby/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:654:in `block in run_tasks_blocks'
/var/www/openvault/shared/bundle/ruby/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:654:in `each'
/var/www/openvault/shared/bundle/ruby/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:654:in `run_tasks_blocks'
/var/www/openvault/shared/bundle/ruby/2.2.0/gems/railties-4.1.2/lib/rails/application.rb:374:in `run_tasks_blocks'
/var/www/openvault/shared/bundle/ruby/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:449:in `load_tasks'
/var/www/openvault/releases/20160224194135/Rakefile:6:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by afred** [comment]
closed by #19
